import time
from sty import Style, RgbFg, fg, bg
import pygame

question=["What is the name of Orbán Viktor?"]
current_line=["Boci Boci", "Viki"]
phone=input("who to call ")
for contacts in ['m','d','t','y']:
    if phone.lower() == 'm':
        #play_sound("./msc/telhiv.mp3", 0)
        time.sleep(2)
        #play_sound("./msc/telefon.mp3", 0)
        then = time.time()
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        print("Hi mummy, I'm playing the Millionaire..Here's the question.. \n"+', '.join(question))
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Hi Honey.. I don't know the answer i'll ask your dad")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("..Dad!..Daddy!..Our son is in the Millionaire Show!! Can you believe??")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print(fg.red+"Mum please my time is almost up!!"+fg.rs)
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Okay honey, it is D.. No, no wait, it is " + current_line[0])
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        now = time.time()
        #play_sound('telefon.mp3', 54.0)
        time.sleep(1)
        print("Call Duration: ", int(now-then), " seconds\\ 30 a")

    if phone.lower() == 'd':
        #play_sound("./msc/telhiv.mp3", 0)
        time.sleep(2)
        #play_sound("./msc/telefon.mp3", 0)
        then = time.time()
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        print("Hi dad, I'm playing the Millionaire..Here's the question.. \n"', '.join(question))
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Hi Son.. I don't know the answer i'll ask your grandfather")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("..Dad!..Daddy!..Your grandson is in the Millionaire Show!! Can you believe??")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print(fg.red+"Dad please my time is almost up!!"+fg.rs)
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Okay Son, he says it is A.. No, no wait, it is " + current_line[0])
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        now = time.time()
        pygame.mixer.music.stop()
        #play_sound('./msc/telefon.mp3', 54.0)
        time.sleep(1)
        print("Call Duration: ", int(now-then), " seconds\\ 30 seconds")

    if phone.lower() == 't':
        #play_sound("./msc/telhiv.mp3", 0)
        time.sleep(2)
        #play_sound("./msc/telefon.mp3", 0)
        then = time.time()
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        print("Great day Mr Teacher I am your former student, and I'm playing the Millionaire..Here's the question..\n"', '.join(question))
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Welcome.. I'd never thought after so many years you'd call me!")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("I have to tell the principle..Mr!..Mr Principle!..One of your former student is in the Millionaire Show!! Can you believe??")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print(fg.red+"Sir please my time is almost up!!"+fg.rs)
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Okay boy, he says it is A.. No, no wait, it is " + current_line[0])
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        now = time.time()
        #pygame.mixer.music.stop()
        #play_sound('./msc/telefon.mp3', 54.0)
        time.sleep(1)
        print("Call Duration: ", int(now-then), " seconds\\ 30 seconds")

    if phone.lower() == 'y':
        #play_sound("./msc/telhiv.mp3", 0)
        time.sleep(2)
        #play_sound("./msc/telefon.mp3", 0)
        then = time.time()
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        print("May the force be with you, my son. How can I help u?")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("Hi Yoda, I need your force of knowledge because I'm playing the Millionaire..Here's the question..\n"', '.join(question))
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("I call the Force for help")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("*background* Hi Leila I'm Yoda please help this is the question..")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        time.sleep(2)
        print("The Force says " + current_line[0] + "\nNever forget, do or don't but never try!")
        print(fg.white+str(30-int(time.time()-then))+fg.rs)
        now = time.time()
        #pygame.mixer.music.stop()
        #play_sound('./msc/telefon.mp3', 54.0)
        time.sleep(1)
        print("Call Duration: ", int(now-then), " seconds\\ 30 seconds max.")